"Shows how you might create a macro for the autogeneratd Jest rule"

load("@npm//jest:index.bzl", _jest_test = "jest_test")

def jest_test(
        name,
        srcs,
        deps,
        jest_config,
        coverage = False,
        **kwargs):
    """A macro around the autogenerated jest_test rule.

    Args:
        name: the name.
        srcs: the srcs.
        deps: the deps.
        jest_config: the jest_config.
        coverage: the coverage.
        kwargs: the kwargs.
    """

    templated_args = [
        "--ci",
        "--collect-coverage" if coverage else "",
        "--no-cache",
        "--no-watchman",
    ]
    templated_args.extend(["--config", "$(rootpath %s)" % jest_config])
    for src in srcs:
        templated_args.extend(["--runTestsByPath", "$(rootpath %s)" % src])

    _jest_test(
        name = name,
        data = srcs + deps + [jest_config],
        templated_args = templated_args,
        **kwargs
    )
